# Important Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings ('ignore')

plt.rcParams['figure.figsize']=[15,6]

pd.set_option('display.max_columns',50) # displaying all data

# Reading Dataset

In [2]:
train=pd.read_csv('Train (2).csv')
test=pd.read_csv('Test (3).csv')

fhc=pd.read_csv('First_Health_Camp.csv')
shc=pd.read_csv('Second_Health_Camp.csv')
thc=pd.read_csv('Third_Health_Camp.csv')
hcdetails=pd.read_csv('Health_Camp_Detail.csv')
pp=pd.read_csv('Patient_Details.csv')

# Data Information

In [3]:
# Checking the shape of Train and Test

train.shape,test.shape

((52694, 9), (22584, 8))

In [4]:
# Checking datatypes

print('\ntrain datatypes:',train.dtypes)
print('\ntest datatypes:',test.dtypes)


train datatypes: Patient_ID            int64
Health_Camp_ID        int64
Registration_Date    object
Var1                  int64
Var2                  int64
Var3                  int64
Var4                  int64
Var5                  int64
outcome               int64
dtype: object

test datatypes: Patient_ID            int64
Health_Camp_ID        int64
Registration_Date    object
Var1                  int64
Var2                  int64
Var3                  int64
Var4                  int64
Var5                  int64
dtype: object


# Data Preprocessing

In [5]:
# Combine Train and Test
combined=pd.concat([train,test],ignore_index=True)

In [6]:
combined.shape

(75278, 9)

In [7]:
# First healthcare

fhc.head(2)

Patient_ID  Health_Camp_ID  Donation  Health_Score  Unnamed: 4
0      506181            6560        40      0.439024         NaN
1      494977            6560        20      0.097561         NaN

In [8]:
combined.head(2)

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   

   outcome  
0      0.0  
1      1.0

In [9]:
# Merge fhc with combine data

combined=pd.merge(left=combined,right=fhc,on=['Patient_ID','Health_Camp_ID'],how='left')

In [10]:
combined.head(2)

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  
0      0.0       NaN           NaN         NaN  
1      1.0       NaN           NaN         NaN

In [11]:
# Second healthcare

shc.head(2)

Patient_ID  Health_Camp_ID  Health Score
0      526631            6536      0.875136
1      509122            6536      0.755700

In [12]:
# Merge shc with combine data

combined=pd.merge(left=combined,right=shc,on=['Patient_ID','Health_Camp_ID'],how='left')

In [13]:
combined.head(2)

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  
0      0.0       NaN           NaN         NaN           NaN  
1      1.0       NaN           NaN         NaN      0.402054

In [14]:
# Third healthcare

thc.head(2)

Patient_ID  Health_Camp_ID  Number_of_stall_visited  \
0      517875            6527                        3   
1      504692            6578                        1   

   Last_Stall_Visited_Number  
0                          1  
1                          1

In [15]:
combined=pd.merge(left=combined,right=thc,on=['Patient_ID','Health_Camp_ID'],how='left')

In [16]:
combined.head(2)

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  \
0      0.0       NaN           NaN         NaN           NaN   
1      1.0       NaN           NaN         NaN      0.402054   

   Number_of_stall_visited  Last_Stall_Visited_Number  
0                      NaN                        NaN  
1                      NaN                        NaN

In [17]:
combined.shape

(75278, 15)

In [18]:
# Health camp

hcdetails.head(2)

Health_Camp_ID Camp_Start_Date Camp_End_Date Category1 Category2  Category3
0            6560       16-Aug-03     20-Aug-03     First         B          2
1            6530       16-Aug-03     28-Oct-03     First         C          2

In [19]:
combined=pd.merge(left=combined,right=hcdetails,on=['Health_Camp_ID'],how='left')

In [20]:
combined.shape

(75278, 20)

In [21]:
#Patient_Details

pp.head(2)

Patient_ID  Online_Follower  LinkedIn_Shared  Twitter_Shared  \
0      516956                0                0               0   
1      507733                0                0               0   

   Facebook_Shared Income Education_Score Age First_Interaction City_Type  \
0                0      1              90  39         18-Jun-03       NaN   
1                0      1            None  40         20-Jul-03         H   

   Employer_Category  
0  Software Industry  
1  Software Industry

In [22]:
combined=pd.merge(left=combined,right=pp,on=['Patient_ID'],how='left')

In [23]:
combined.shape

(75278, 30)

In [24]:
combined.head()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   
2      520968            6557          07/01/04     0     0     0     0     0   
3      507625            6535          12/02/04     0     0     0     0     0   
4      502611            6581          14/03/04     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  \
0      0.0       NaN           NaN         NaN           NaN   
1      1.0       NaN           NaN         NaN      0.402054   
2      1.0      20.0      0.611111         NaN           NaN   
3      0.0       NaN           NaN         NaN           NaN   
4      0.0       NaN           NaN         NaN           NaN   

   Number_of_stall_visited  Last_Stall_Visited_Number Camp_Start_Date  \
0                      NaN                        NaN       09-Jul-05   
1                      NaN                        NaN       17-Oct-05   
2                      NaN                        NaN       04-Jan-04   
3                      NaN                        NaN       01-Feb-04   
4                      NaN                        NaN       07-Dec-03   

  Camp_End_Date Category1 Category2  Category3  Online_Follower  \
0     22-Jul-05     First         E          2                0   
1     07-Nov-07    Second         A          2                0   
2     09-Jan-04     First         C          2                0   
3     18-Feb-04     First         E          2                0   
4     13-Jun-04     First         F          2                0   

   LinkedIn_Shared  Twitter_Shared  Facebook_Shared Income Education_Score  \
0                0               0                0   None            None   
1                0               0                0   None            None   
2                0               0                0   None            None   
3                0               0                0   None            None   
4                0               0                0   None            None   

    Age First_Interaction City_Type Employer_Category  
0  None         14-Nov-04       NaN               NaN  
1  None         26-May-06         H               NaN  
2  None         07-Jan-04         H               NaN  
3  None         12-Feb-04         B               NaN  
4  None         14-Mar-04         B               NaN

# Feature Engineering

In [25]:
# Registration Date and changing its datatype to datetime

combined['Registration_Date']=pd.to_datetime(combined.Registration_Date,dayfirst=True)

combined['Registration_Month']=combined.Registration_Date.dt.month
combined['Registration_Year']=combined.Registration_Date.dt.year
combined['Registration_Day']=combined.Registration_Date.dt.day

In [26]:
# Camp start and end date

combined['Camp_Start_Month']=pd.DatetimeIndex(combined.Camp_Start_Date).month
combined['Camp_Start_Year']=pd.DatetimeIndex(combined.Camp_Start_Date).year
combined['Camp_Start_Day']=pd.DatetimeIndex(combined.Camp_Start_Date).day

combined['Camp_End_Month']=pd.DatetimeIndex(combined.Camp_End_Date).month
combined['Camp_End_Year']=pd.DatetimeIndex(combined.Camp_End_Date).year
combined['Camp_End_Day']=pd.DatetimeIndex(combined.Camp_End_Date).day

In [27]:
# Creating online_presence using pateint profiling data

combined['Online_Presence']=combined['Online_Follower']+combined['LinkedIn_Shared']+combined['Twitter_Shared']+combined['Facebook_Shared']

In [28]:
# Dropping columns above

combined.drop(['Online_Follower','LinkedIn_Shared','Twitter_Shared','Facebook_Shared'],axis=1,inplace=True)


In [29]:
pp.head()

Patient_ID  Online_Follower  LinkedIn_Shared  Twitter_Shared  \
0      516956                0                0               0   
1      507733                0                0               0   
2      508307                0                0               0   
3      512612                0                0               0   
4      521075                0                0               0   

   Facebook_Shared Income Education_Score Age First_Interaction City_Type  \
0                0      1              90  39         18-Jun-03       NaN   
1                0      1            None  40         20-Jul-03         H   
2                0      3              87  46         02-Nov-02         D   
3                0      1              75  47         02-Nov-02         D   
4                0      3            None  80         24-Nov-02         H   

   Employer_Category  
0  Software Industry  
1  Software Industry  
2               BFSI  
3          Education  
4             Others

In [30]:
del pp

In [31]:
combined.head()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570        2005-05-14     0     0     0     0     0   
1      510379            6534        2006-05-26     0     0     0     0     0   
2      520968            6557        2004-01-07     0     0     0     0     0   
3      507625            6535        2004-02-12     0     0     0     0     0   
4      502611            6581        2004-03-14     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  \
0      0.0       NaN           NaN         NaN           NaN   
1      1.0       NaN           NaN         NaN      0.402054   
2      1.0      20.0      0.611111         NaN           NaN   
3      0.0       NaN           NaN         NaN           NaN   
4      0.0       NaN           NaN         NaN           NaN   

   Number_of_stall_visited  Last_Stall_Visited_Number Camp_Start_Date  \
0                      NaN                        NaN       09-Jul-05   
1                      NaN                        NaN       17-Oct-05   
2                      NaN                        NaN       04-Jan-04   
3                      NaN                        NaN       01-Feb-04   
4                      NaN                        NaN       07-Dec-03   

  Camp_End_Date Category1 Category2  Category3 Income Education_Score   Age  \
0     22-Jul-05     First         E          2   None            None  None   
1     07-Nov-07    Second         A          2   None            None  None   
2     09-Jan-04     First         C          2   None            None  None   
3     18-Feb-04     First         E          2   None            None  None   
4     13-Jun-04     First         F          2   None            None  None   

  First_Interaction City_Type Employer_Category  Registration_Month  \
0         14-Nov-04       NaN               NaN                 5.0   
1         26-May-06         H               NaN                 5.0   
2         07-Jan-04         H               NaN                 1.0   
3         12-Feb-04         B               NaN                 2.0   
4         14-Mar-04         B               NaN                 3.0   

   Registration_Year  Registration_Day  Camp_Start_Month  Camp_Start_Year  \
0             2005.0              14.0                 7             2005   
1             2006.0              26.0                10             2005   
2             2004.0               7.0                 1             2004   
3             2004.0              12.0                 2             2004   
4             2004.0              14.0                12             2003   

   Camp_Start_Day  Camp_End_Month  Camp_End_Year  Camp_End_Day  \
0               9               7           2005            22   
1              17              11           2007             7   
2               4               1           2004             9   
3               1               2           2004            18   
4               7               6           2004            13   

   Online_Presence  
0                0  
1                0  
2                0  
3                0  
4                0

In [32]:
# Camp duration from CampEndDate-CampStartDate

combined['Camp_Start_Date']=pd.to_datetime(combined.Camp_Start_Date,dayfirst=True)
combined['Camp_End_Date']=pd.to_datetime(combined.Camp_End_Date,dayfirst=True)


combined['Camp_Duration']=(combined['Camp_End_Date']-combined['Camp_Start_Date']).dt.days

In [33]:
combined.head()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570        2005-05-14     0     0     0     0     0   
1      510379            6534        2006-05-26     0     0     0     0     0   
2      520968            6557        2004-01-07     0     0     0     0     0   
3      507625            6535        2004-02-12     0     0     0     0     0   
4      502611            6581        2004-03-14     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  \
0      0.0       NaN           NaN         NaN           NaN   
1      1.0       NaN           NaN         NaN      0.402054   
2      1.0      20.0      0.611111         NaN           NaN   
3      0.0       NaN           NaN         NaN           NaN   
4      0.0       NaN           NaN         NaN           NaN   

   Number_of_stall_visited  Last_Stall_Visited_Number Camp_Start_Date  \
0                      NaN                        NaN      2005-07-09   
1                      NaN                        NaN      2005-10-17   
2                      NaN                        NaN      2004-01-04   
3                      NaN                        NaN      2004-02-01   
4                      NaN                        NaN      2003-12-07   

  Camp_End_Date Category1 Category2  Category3 Income Education_Score   Age  \
0    2005-07-22     First         E          2   None            None  None   
1    2007-11-07    Second         A          2   None            None  None   
2    2004-01-09     First         C          2   None            None  None   
3    2004-02-18     First         E          2   None            None  None   
4    2004-06-13     First         F          2   None            None  None   

  First_Interaction City_Type Employer_Category  Registration_Month  \
0         14-Nov-04       NaN               NaN                 5.0   
1         26-May-06         H               NaN                 5.0   
2         07-Jan-04         H               NaN                 1.0   
3         12-Feb-04         B               NaN                 2.0   
4         14-Mar-04         B               NaN                 3.0   

   Registration_Year  Registration_Day  Camp_Start_Month  Camp_Start_Year  \
0             2005.0              14.0                 7             2005   
1             2006.0              26.0                10             2005   
2             2004.0               7.0                 1             2004   
3             2004.0              12.0                 2             2004   
4             2004.0              14.0                12             2003   

   Camp_Start_Day  Camp_End_Month  Camp_End_Year  Camp_End_Day  \
0               9               7           2005            22   
1              17              11           2007             7   
2               4               1           2004             9   
3               1               2           2004            18   
4               7               6           2004            13   

   Online_Presence  Camp_Duration  
0                0             13  
1                0            751  
2                0              5  
3                0             17  
4                0            189

In [34]:
# Days_interaction_diff=registration date-first interaction

# Converting First Interaction Date into datetime format

combined['First_Interaction']=pd.to_datetime(combined.First_Interaction,dayfirst=True)

combined['Int_Day_Diff']=combined['Registration_Date']-combined['First_Interaction']

In [35]:
combined.head()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570        2005-05-14     0     0     0     0     0   
1      510379            6534        2006-05-26     0     0     0     0     0   
2      520968            6557        2004-01-07     0     0     0     0     0   
3      507625            6535        2004-02-12     0     0     0     0     0   
4      502611            6581        2004-03-14     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  \
0      0.0       NaN           NaN         NaN           NaN   
1      1.0       NaN           NaN         NaN      0.402054   
2      1.0      20.0      0.611111         NaN           NaN   
3      0.0       NaN           NaN         NaN           NaN   
4      0.0       NaN           NaN         NaN           NaN   

   Number_of_stall_visited  Last_Stall_Visited_Number Camp_Start_Date  \
0                      NaN                        NaN      2005-07-09   
1                      NaN                        NaN      2005-10-17   
2                      NaN                        NaN      2004-01-04   
3                      NaN                        NaN      2004-02-01   
4                      NaN                        NaN      2003-12-07   

  Camp_End_Date Category1 Category2  Category3 Income Education_Score   Age  \
0    2005-07-22     First         E          2   None            None  None   
1    2007-11-07    Second         A          2   None            None  None   
2    2004-01-09     First         C          2   None            None  None   
3    2004-02-18     First         E          2   None            None  None   
4    2004-06-13     First         F          2   None            None  None   

  First_Interaction City_Type Employer_Category  Registration_Month  \
0        2004-11-14       NaN               NaN                 5.0   
1        2006-05-26         H               NaN                 5.0   
2        2004-01-07         H               NaN                 1.0   
3        2004-02-12         B               NaN                 2.0   
4        2004-03-14         B               NaN                 3.0   

   Registration_Year  Registration_Day  Camp_Start_Month  Camp_Start_Year  \
0             2005.0              14.0                 7             2005   
1             2006.0              26.0                10             2005   
2             2004.0               7.0                 1             2004   
3             2004.0              12.0                 2             2004   
4             2004.0              14.0                12             2003   

   Camp_Start_Day  Camp_End_Month  Camp_End_Year  Camp_End_Day  \
0               9               7           2005            22   
1              17              11           2007             7   
2               4               1           2004             9   
3               1               2           2004            18   
4               7               6           2004            13   

   Online_Presence  Camp_Duration Int_Day_Diff  
0                0             13     181 days  
1                0            751       0 days  
2                0              5       0 days  
3                0             17       0 days  
4                0            189       0 days

In [36]:
combined.Registration_Year.value_counts()

2005.0    36069
2004.0    19036
2006.0    15924
2003.0     3065
2007.0      850
Name: Registration_Year, dtype: int64

In [37]:
# Donation VS healthcamp

combined.groupby('Health_Camp_ID')['Donation'].describe().T

Health_Camp_ID  6523       6524        6526  6527  6528  6529       6530  \
count            0.0  54.000000  140.000000   0.0   0.0   0.0  42.000000   
mean             NaN  25.555556   31.214286   NaN   NaN   NaN  19.523810   
std              NaN  10.580628   24.034384   NaN   NaN   NaN  10.109735   
min              NaN  10.000000   10.000000   NaN   NaN   NaN  10.000000   
25%              NaN  20.000000   10.000000   NaN   NaN   NaN  10.000000   
50%              NaN  20.000000   20.000000   NaN   NaN   NaN  20.000000   
75%              NaN  30.000000   40.000000   NaN   NaN   NaN  27.500000   
max              NaN  60.000000  150.000000   NaN   NaN   NaN  50.000000   

Health_Camp_ID       6531        6532  6534        6535  6536        6537  \
count           79.000000  262.000000   0.0  252.000000   0.0  481.000000   
mean            18.354430   32.824427   NaN   25.833333   NaN   36.611227   
std              8.232266   29.446355   NaN   15.579765   NaN   29.825056   
min             10.000000   10.000000   NaN   10.000000   NaN   10.000000   
25%             10.000000   10.000000   NaN   10.000000   NaN   20.000000   
50%             20.000000   30.000000   NaN   20.000000   NaN   30.000000   
75%             20.000000   40.000000   NaN   30.000000   NaN   50.000000   
max             40.000000  330.000000   NaN   80.000000   NaN  170.000000   

Health_Camp_ID        6538        6539        6540  6541        6542  \
count           625.000000  254.000000  140.000000   0.0  362.000000   
mean             37.232000   34.921260   29.714286   NaN   33.370166   
std              29.954863   23.316725   16.790836   NaN   28.161013   
min              10.000000   10.000000   10.000000   NaN   10.000000   
25%              20.000000   20.000000   20.000000   NaN   20.000000   
50%              30.000000   30.000000   30.000000   NaN   30.000000   
75%              50.000000   50.000000   40.000000   NaN   40.000000   
max             250.000000  120.000000  110.000000   NaN  280.000000   

Health_Camp_ID        6543       6544       6546  6549        6552       6553  \
count           826.000000  13.000000  18.000000   0.0   43.000000  11.000000   
mean             36.283293  32.307692  23.333333   NaN   30.000000  12.727273   
std              27.618389  13.008873   9.701425   NaN   20.701967   4.670994   
min              10.000000  10.000000  10.000000   NaN   10.000000  10.000000   
25%              20.000000  20.000000  20.000000   NaN   20.000000  10.000000   
50%              30.000000  30.000000  20.000000   NaN   30.000000  10.000000   
75%              50.000000  40.000000  27.500000   NaN   30.000000  15.000000   
max             180.000000  50.000000  50.000000   NaN  110.000000  20.000000   

Health_Camp_ID        6554  6555       6557       6558       6560        6561  \
count           346.000000   0.0  36.000000  20.000000  41.000000   55.000000   
mean             33.352601   NaN  19.166667  20.500000  31.463415   25.818182   
std              23.938991   NaN   6.491753   8.870412  13.885420   21.831926   
min              10.000000   NaN  10.000000  10.000000  10.000000   10.000000   
25%              20.000000   NaN  17.500000  10.000000  20.000000   10.000000   
50%              30.000000   NaN  20.000000  20.000000  30.000000   20.000000   
75%              40.000000   NaN  20.000000  30.000000  40.000000   30.000000   
max             160.000000   NaN  30.000000  40.000000  70.000000  100.000000   

Health_Camp_ID       6562        6563       6564       6565        6569  \
count           89.000000  117.000000  49.000000  41.000000  112.000000   
mean            34.044944   29.572650  21.428571  19.512195   20.625000   
std             20.982628   10.699111  12.247449   9.206307    9.032599   
min             10.000000   10.000000  10.000000  10.000000   10.000000   
25%             20.000000   20.000000  10.000000  10.000000   17.500000   
50%             30.000000   30.000000  20.000000  20.000000   

In [38]:
combined.Health_Camp_ID.nunique()

44

In [39]:
# Unique patient at healthcamp



combined['Health_Camp_ID'].value_counts()

6543    6543
6527    4144
6538    3954
6537    3859
6529    3823
6526    3809
6534    3597
6570    3564
6580    3517
6578    2837
6586    2624
6542    2368
6562    2338
6554    2303
6571    2086
6523    2084
6536    2037
6532    1993
6539    1992
6535    1882
6549    1835
6528    1744
6555    1738
6541    1547
6581    1485
6540    1426
6585    1398
6564     514
6546     403
6530     259
6561     200
6569     177
6563     171
6524     149
6544     128
6560     123
6531     120
6553      94
6575      90
6552      82
6587      79
6565      66
6557      52
6558      44
Name: Health_Camp_ID, dtype: int64

In [40]:
combined['HC_per_patient']=combined.groupby('Patient_ID')['Health_Camp_ID'].transform('nunique')
combined['Patient_per_HC']=combined.groupby('Health_Camp_ID')['Patient_ID'].transform('nunique')

In [41]:
combined.groupby('Health_Camp_ID')['Patient_ID'].nunique()

Health_Camp_ID
6523    2084
6524     149
6526    3809
6527    4144
6528    1744
6529    3823
6530     259
6531     120
6532    1993
6534    3597
6535    1882
6536    2037
6537    3859
6538    3954
6539    1992
6540    1426
6541    1547
6542    2368
6543    6543
6544     128
6546     403
6549    1835
6552      82
6553      94
6554    2303
6555    1738
6557      52
6558      44
6560     123
6561     200
6562    2338
6563     171
6564     514
6565      66
6569     177
6570    3564
6571    2086
6575      90
6578    2837
6580    3517
6581    1485
6585    1398
6586    2624
6587      79
Name: Patient_ID, dtype: int64

In [42]:
combined.head()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570        2005-05-14     0     0     0     0     0   
1      510379            6534        2006-05-26     0     0     0     0     0   
2      520968            6557        2004-01-07     0     0     0     0     0   
3      507625            6535        2004-02-12     0     0     0     0     0   
4      502611            6581        2004-03-14     0     0     0     0     0   

   outcome  Donation  Health_Score  Unnamed: 4  Health Score  \
0      0.0       NaN           NaN         NaN           NaN   
1      1.0       NaN           NaN         NaN      0.402054   
2      1.0      20.0      0.611111         NaN           NaN   
3      0.0       NaN           NaN         NaN           NaN   
4      0.0       NaN           NaN         NaN           NaN   

   Number_of_stall_visited  Last_Stall_Visited_Number Camp_Start_Date  \
0                      NaN                        NaN      2005-07-09   
1                      NaN                        NaN      2005-10-17   
2                      NaN                        NaN      2004-01-04   
3                      NaN                        NaN      2004-02-01   
4                      NaN                        NaN      2003-12-07   

  Camp_End_Date Category1 Category2  Category3 Income Education_Score   Age  \
0    2005-07-22     First         E          2   None            None  None   
1    2007-11-07    Second         A          2   None            None  None   
2    2004-01-09     First         C          2   None            None  None   
3    2004-02-18     First         E          2   None            None  None   
4    2004-06-13     First         F          2   None            None  None   

  First_Interaction City_Type Employer_Category  Registration_Month  \
0        2004-11-14       NaN               NaN                 5.0   
1        2006-05-26         H               NaN                 5.0   
2        2004-01-07         H               NaN                 1.0   
3        2004-02-12         B               NaN                 2.0   
4        2004-03-14         B               NaN                 3.0   

   Registration_Year  Registration_Day  Camp_Start_Month  Camp_Start_Year  \
0             2005.0              14.0                 7             2005   
1             2006.0              26.0                10             2005   
2             2004.0               7.0                 1             2004   
3             2004.0              12.0                 2             2004   
4             2004.0              14.0                12             2003   

   Camp_Start_Day  Camp_End_Month  Camp_End_Year  Camp_End_Day  \
0               9               7           2005            22   
1              17              11           2007             7   
2               4               1           2004             9   
3               1               2           2004            18   
4               7               6           2004            13   

   Online_Presence  Camp_Duration Int_Day_Diff  HC_per_patient  Patient_per_HC  
0                0             13     181 days               2            3564  
1                0            751       0 days               1            3597  
2                0              5       0 days               1              52  
3                0             17       0 days               1            1882  
4                0            189       0 days               2            1485

In [43]:
combined['HC_per_patient'].describe()

count    75278.000000
mean         5.660618
std          5.077292
min          1.000000
25%          2.000000
50%          4.000000
75%          8.000000
max         32.000000
Name: HC_per_patient, dtype: float64

In [44]:
combined['Patient_per_HC'].describe()

count    75278.000000
mean      3081.875873
std       1457.243273
min         44.000000
25%       1993.000000
50%       2837.000000
75%       3823.000000
max       6543.000000
Name: Patient_per_HC, dtype: float64

In [45]:
# Unique Patients visited in the beginning of the year Camp Started

combined['Patients_Per_Year']=combined.groupby('Camp_Start_Year')['Patient_ID'].transform('nunique')

combined.groupby('Camp_Start_Year')['Patient_ID'].nunique()

Camp_Start_Year
2003     3081
2004    10902
2005    22359
2006     4681
Name: Patient_ID, dtype: int64

In [46]:
# Unique Patients visited monthwise Camp Started

combined['Patients_Per_Month']=combined.groupby('Camp_Start_Month')['Patient_ID'].transform('nunique')

combined.groupby('Camp_Start_Month')['Patient_ID'].nunique()

Camp_Start_Month
1     6902
2     8717
3     3823
4      160
5      229
6     5952
7     3564
8     4860
9     9898
10    7346
11    4543
12    6272
Name: Patient_ID, dtype: int64

In [47]:
# Unique Patients visited in the End of the year Camp Ended

combined['Patients_Per_End_Year']=combined.groupby('Camp_End_Year')['Patient_ID'].transform('nunique')

combined.groupby('Camp_End_Year')['Patient_ID'].nunique()

Camp_End_Year
2003     1753
2004     6319
2005    17330
2006     5663
2007    10197
Name: Patient_ID, dtype: int64

In [48]:
# Unique Patients visited monthwise Camp Started

combined['Patients_Per_End_Month']=combined.groupby('Camp_Start_Month')['Patient_ID'].transform('nunique')

combined.groupby('Camp_Start_Month')['Patient_ID'].nunique()

Camp_Start_Month
1     6902
2     8717
3     3823
4      160
5      229
6     5952
7     3564
8     4860
9     9898
10    7346
11    4543
12    6272
Name: Patient_ID, dtype: int64

In [49]:
combined.groupby('Camp_Start_Year')['Camp_Start_Year'].value_counts()

Camp_Start_Year  Camp_Start_Year
2003             2003                4107
2004             2004               18942
2005             2005               46662
2006             2006                5567
Name: Camp_Start_Year, dtype: int64

In [50]:
combined.shape

(75278, 44)

# Target Variable

In [51]:
def target(a,b,c,d):
    if (a>0)|(b>0)|(c>0)|(d>0):
        return(1)
    else:
        return(0)

In [52]:
# Generate Target Variable

combined['outcome']=combined.apply(lambda x:target(x['Health_Score'],x['Health Score'],x['Number_of_stall_visited'],x['Last_Stall_Visited_Number']),axis=1)

In [53]:
combined.outcome.value_counts()

0    54744
1    20534
Name: outcome, dtype: int64

In [54]:
combined.columns

Index(['Patient_ID', 'Health_Camp_ID', 'Registration_Date', 'Var1', 'Var2',
       'Var3', 'Var4', 'Var5', 'outcome', 'Donation', 'Health_Score',
       'Unnamed: 4', 'Health Score', 'Number_of_stall_visited',
       'Last_Stall_Visited_Number', 'Camp_Start_Date', 'Camp_End_Date',
       'Category1', 'Category2', 'Category3', 'Income', 'Education_Score',
       'Age', 'First_Interaction', 'City_Type', 'Employer_Category',
       'Registration_Month', 'Registration_Year', 'Registration_Day',
       'Camp_Start_Month', 'Camp_Start_Year', 'Camp_Start_Day',
       'Camp_End_Month', 'Camp_End_Year', 'Camp_End_Day', 'Online_Presence',
       'Camp_Duration', 'Int_Day_Diff', 'HC_per_patient', 'Patient_per_HC',
       'Patients_Per_Year', 'Patients_Per_Month', 'Patients_Per_End_Year',
       'Patients_Per_End_Month'],
      dtype='object')

In [55]:
# Drop the unnecessary variables

new=combined.drop(['Patient_ID', 'Health_Camp_ID', 'Registration_Date','Donation','Health_Score', 
                   'Unnamed: 4','Health Score', 'Number_of_stall_visited', 'Last_Stall_Visited_Number',
                'Camp_Start_Date', 'Camp_End_Date','Income', 'Education_Score','First_Interaction',
                  'City_Type', 'Employer_Category','Age'],axis=1)


In [56]:
combined.City_Type.unique()

array([nan, 'H', 'B', 'G', 'C', 'E', 'A', 'D', 'F', 'I'], dtype=object)

In [57]:
del combined,fhc,shc,hcdetails,thc

In [58]:
new.shape

(75278, 27)

In [59]:
new.columns

Index(['Var1', 'Var2', 'Var3', 'Var4', 'Var5', 'outcome', 'Category1',
       'Category2', 'Category3', 'Registration_Month', 'Registration_Year',
       'Registration_Day', 'Camp_Start_Month', 'Camp_Start_Year',
       'Camp_Start_Day', 'Camp_End_Month', 'Camp_End_Year', 'Camp_End_Day',
       'Online_Presence', 'Camp_Duration', 'Int_Day_Diff', 'HC_per_patient',
       'Patient_per_HC', 'Patients_Per_Year', 'Patients_Per_Month',
       'Patients_Per_End_Year', 'Patients_Per_End_Month'],
      dtype='object')

In [60]:
new.Category2.value_counts()

F    24660
E    20988
A    10993
G    10272
D     4121
B     2426
C     1818
Name: Category2, dtype: int64

In [61]:
new.Category1.value_counts()

First     49892
Second    15114
Third     10272
Name: Category1, dtype: int64

In [62]:
mapped={'First':1,'Second':2,'Third':3}
new['Category1']=new.Category1.map(mapped)

In [63]:
# Category2

new['Category2']=pd.factorize(new.Category2,sort=True)[0]

In [64]:
new.isnull().sum()

Var1                        0
Var2                        0
Var3                        0
Var4                        0
Var5                        0
outcome                     0
Category1                   0
Category2                   0
Category3                   0
Registration_Month        334
Registration_Year         334
Registration_Day          334
Camp_Start_Month            0
Camp_Start_Year             0
Camp_Start_Day              0
Camp_End_Month              0
Camp_End_Year               0
Camp_End_Day                0
Online_Presence             0
Camp_Duration               0
Int_Day_Diff              334
HC_per_patient              0
Patient_per_HC              0
Patients_Per_Year           0
Patients_Per_Month          0
Patients_Per_End_Year       0
Patients_Per_End_Month      0
dtype: int64

# Missing Value Treatment

In [65]:
new['Registration_Year'].fillna(new.Registration_Year.mode()[0],inplace=True)
new['Registration_Month'].fillna(new.Registration_Month.mode()[0],inplace=True)
new['Registration_Day'].fillna(new.Registration_Day.mode()[0],inplace=True)

In [66]:
new['Int_Day_Diff'].fillna(new.Int_Day_Diff.median(),inplace=True)

In [67]:
new['Int_Day_Diff']=new['Int_Day_Diff'].dt.days

In [68]:
new['Int_Day_Diff']

0        181
1          0
2          0
3          0
4          0
        ... 
75273    215
75274    705
75275     13
75276     26
75277    708
Name: Int_Day_Diff, Length: 75278, dtype: int64

In [69]:
new.isnull().sum()

Var1                      0
Var2                      0
Var3                      0
Var4                      0
Var5                      0
outcome                   0
Category1                 0
Category2                 0
Category3                 0
Registration_Month        0
Registration_Year         0
Registration_Day          0
Camp_Start_Month          0
Camp_Start_Year           0
Camp_Start_Day            0
Camp_End_Month            0
Camp_End_Year             0
Camp_End_Day              0
Online_Presence           0
Camp_Duration             0
Int_Day_Diff              0
HC_per_patient            0
Patient_per_HC            0
Patients_Per_Year         0
Patients_Per_Month        0
Patients_Per_End_Year     0
Patients_Per_End_Month    0
dtype: int64

# Train Test Split

In [70]:
train.shape,test.shape

((52694, 9), (22584, 8))

In [71]:
newtrain=new.loc[0:train.shape[0]-1,:]
newtest=new.loc[train.shape[0]:,:]


In [72]:
newtrain.shape,newtest.shape

((52694, 27), (22584, 27))

In [73]:
# Drop Target from test

newtest.drop('outcome',axis=1,inplace=True)

In [74]:
newtrain.shape,newtest.shape

((52694, 27), (22584, 26))

## Model Building

1. Logistic Regression Model
2. Random Forest Model
3. Gradient Boosting Model
4. Xtreme Gradient Boosting Model
5. Catboost Model

In [75]:
# Data in X and Y

X=newtrain.drop('outcome',axis=1)
y=newtrain['outcome']

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

In [77]:
# Models

lr=LogisticRegression()
rf=RandomForestClassifier()
gbm=GradientBoostingClassifier()
xgb=CatBoostClassifier()
cboost=XGBClassifier()

In [78]:
# Lets build a Voting Classifier Model

from sklearn.ensemble import VotingClassifier

vc=VotingClassifier(estimators=[('lr',lr),('rf',rf),('gbm',gbm),('xgb',xgb),('cboost',cboost)],voting="soft") # soft is giving probability, hard will give either 0 or 1.

In [79]:
vc.fit(X,y)

Learning rate set to 0.055992
0:	learn: 0.6623520	total: 189ms	remaining: 3m 9s
1:	learn: 0.6356829	total: 213ms	remaining: 1m 46s
2:	learn: 0.6087900	total: 237ms	remaining: 1m 18s
3:	learn: 0.5854762	total: 254ms	remaining: 1m 3s
4:	learn: 0.5656664	total: 275ms	remaining: 54.8s
5:	learn: 0.5506516	total: 291ms	remaining: 48.2s
6:	learn: 0.5370674	total: 309ms	remaining: 43.8s
7:	learn: 0.5257292	total: 327ms	remaining: 40.5s
8:	learn: 0.5149955	total: 345ms	remaining: 37.9s
9:	learn: 0.5049570	total: 363ms	remaining: 35.9s
10:	learn: 0.4969170	total: 385ms	remaining: 34.6s
11:	learn: 0.4892112	total: 404ms	remaining: 33.3s
12:	learn: 0.4832679	total: 420ms	remaining: 31.9s
13:	learn: 0.4781978	total: 437ms	remaining: 30.8s
14:	learn: 0.4726485	total: 455ms	remaining: 29.9s
15:	learn: 0.4685249	total: 469ms	remaining: 28.8s
16:	learn: 0.4638326	total: 491ms	remaining: 28.4s
17:	learn: 0.4602482	total: 510ms	remaining: 27.8s
18:	learn: 0.4568440	total: 526ms	remaining: 27.1s
19:	learn

165:	learn: 0.4016293	total: 3.08s	remaining: 15.5s
166:	learn: 0.4016112	total: 3.1s	remaining: 15.4s
167:	learn: 0.4014959	total: 3.11s	remaining: 15.4s
168:	learn: 0.4014338	total: 3.13s	remaining: 15.4s
169:	learn: 0.4013572	total: 3.14s	remaining: 15.3s
170:	learn: 0.4012487	total: 3.16s	remaining: 15.3s
171:	learn: 0.4011416	total: 3.18s	remaining: 15.3s
172:	learn: 0.4010781	total: 3.19s	remaining: 15.3s
173:	learn: 0.4009809	total: 3.21s	remaining: 15.2s
174:	learn: 0.4008858	total: 3.23s	remaining: 15.2s
175:	learn: 0.4007823	total: 3.24s	remaining: 15.2s
176:	learn: 0.4006425	total: 3.26s	remaining: 15.2s
177:	learn: 0.4005893	total: 3.28s	remaining: 15.2s
178:	learn: 0.4004320	total: 3.31s	remaining: 15.2s
179:	learn: 0.4003125	total: 3.33s	remaining: 15.2s
180:	learn: 0.4002662	total: 3.35s	remaining: 15.1s
181:	learn: 0.4002050	total: 3.36s	remaining: 15.1s
182:	learn: 0.4001415	total: 3.38s	remaining: 15.1s
183:	learn: 0.4000673	total: 3.39s	remaining: 15.1s
184:	learn: 0

333:	learn: 0.3864429	total: 5.93s	remaining: 11.8s
334:	learn: 0.3863784	total: 5.94s	remaining: 11.8s
335:	learn: 0.3863005	total: 5.96s	remaining: 11.8s
336:	learn: 0.3862059	total: 5.97s	remaining: 11.8s
337:	learn: 0.3860868	total: 5.99s	remaining: 11.7s
338:	learn: 0.3860013	total: 6.01s	remaining: 11.7s
339:	learn: 0.3858952	total: 6.03s	remaining: 11.7s
340:	learn: 0.3858161	total: 6.04s	remaining: 11.7s
341:	learn: 0.3857560	total: 6.06s	remaining: 11.7s
342:	learn: 0.3857051	total: 6.07s	remaining: 11.6s
343:	learn: 0.3856200	total: 6.09s	remaining: 11.6s
344:	learn: 0.3855588	total: 6.1s	remaining: 11.6s
345:	learn: 0.3854969	total: 6.12s	remaining: 11.6s
346:	learn: 0.3854106	total: 6.13s	remaining: 11.5s
347:	learn: 0.3853418	total: 6.15s	remaining: 11.5s
348:	learn: 0.3852628	total: 6.16s	remaining: 11.5s
349:	learn: 0.3851389	total: 6.18s	remaining: 11.5s
350:	learn: 0.3850758	total: 6.2s	remaining: 11.5s
351:	learn: 0.3850117	total: 6.21s	remaining: 11.4s
352:	learn: 0.

498:	learn: 0.3758273	total: 8.56s	remaining: 8.59s
499:	learn: 0.3757682	total: 8.57s	remaining: 8.57s
500:	learn: 0.3757162	total: 8.59s	remaining: 8.56s
501:	learn: 0.3756313	total: 8.62s	remaining: 8.55s
502:	learn: 0.3755664	total: 8.64s	remaining: 8.53s
503:	learn: 0.3755169	total: 8.66s	remaining: 8.52s
504:	learn: 0.3754384	total: 8.68s	remaining: 8.51s
505:	learn: 0.3754021	total: 8.69s	remaining: 8.49s
506:	learn: 0.3753623	total: 8.71s	remaining: 8.47s
507:	learn: 0.3753267	total: 8.73s	remaining: 8.46s
508:	learn: 0.3752831	total: 8.75s	remaining: 8.44s
509:	learn: 0.3752567	total: 8.77s	remaining: 8.43s
510:	learn: 0.3752206	total: 8.79s	remaining: 8.41s
511:	learn: 0.3751923	total: 8.81s	remaining: 8.39s
512:	learn: 0.3751309	total: 8.83s	remaining: 8.38s
513:	learn: 0.3750950	total: 8.85s	remaining: 8.36s
514:	learn: 0.3750248	total: 8.86s	remaining: 8.35s
515:	learn: 0.3750089	total: 8.88s	remaining: 8.33s
516:	learn: 0.3749676	total: 8.89s	remaining: 8.31s
517:	learn: 

663:	learn: 0.3673677	total: 11.4s	remaining: 5.76s
664:	learn: 0.3672893	total: 11.4s	remaining: 5.75s
665:	learn: 0.3672278	total: 11.4s	remaining: 5.73s
666:	learn: 0.3671901	total: 11.4s	remaining: 5.71s
667:	learn: 0.3671647	total: 11.5s	remaining: 5.7s
668:	learn: 0.3671456	total: 11.5s	remaining: 5.68s
669:	learn: 0.3671024	total: 11.5s	remaining: 5.66s
670:	learn: 0.3670756	total: 11.5s	remaining: 5.64s
671:	learn: 0.3670503	total: 11.5s	remaining: 5.62s
672:	learn: 0.3670076	total: 11.5s	remaining: 5.61s
673:	learn: 0.3669630	total: 11.6s	remaining: 5.59s
674:	learn: 0.3669239	total: 11.6s	remaining: 5.57s
675:	learn: 0.3668888	total: 11.6s	remaining: 5.55s
676:	learn: 0.3668421	total: 11.6s	remaining: 5.54s
677:	learn: 0.3668038	total: 11.6s	remaining: 5.52s
678:	learn: 0.3667621	total: 11.6s	remaining: 5.5s
679:	learn: 0.3667337	total: 11.7s	remaining: 5.48s
680:	learn: 0.3666727	total: 11.7s	remaining: 5.47s
681:	learn: 0.3666202	total: 11.7s	remaining: 5.45s
682:	learn: 0.

827:	learn: 0.3602380	total: 14.2s	remaining: 2.96s
828:	learn: 0.3601985	total: 14.2s	remaining: 2.94s
829:	learn: 0.3601509	total: 14.3s	remaining: 2.92s
830:	learn: 0.3600888	total: 14.3s	remaining: 2.9s
831:	learn: 0.3600421	total: 14.3s	remaining: 2.89s
832:	learn: 0.3599748	total: 14.3s	remaining: 2.87s
833:	learn: 0.3599368	total: 14.3s	remaining: 2.85s
834:	learn: 0.3598768	total: 14.4s	remaining: 2.84s
835:	learn: 0.3598418	total: 14.4s	remaining: 2.82s
836:	learn: 0.3598023	total: 14.4s	remaining: 2.8s
837:	learn: 0.3597505	total: 14.4s	remaining: 2.79s
838:	learn: 0.3597146	total: 14.4s	remaining: 2.77s
839:	learn: 0.3596689	total: 14.5s	remaining: 2.75s
840:	learn: 0.3596333	total: 14.5s	remaining: 2.74s
841:	learn: 0.3596056	total: 14.5s	remaining: 2.72s
842:	learn: 0.3595570	total: 14.5s	remaining: 2.7s
843:	learn: 0.3595256	total: 14.5s	remaining: 2.69s
844:	learn: 0.3594940	total: 14.5s	remaining: 2.67s
845:	learn: 0.3594197	total: 14.6s	remaining: 2.65s
846:	learn: 0.3

991:	learn: 0.3536669	total: 17.1s	remaining: 138ms
992:	learn: 0.3536303	total: 17.1s	remaining: 121ms
993:	learn: 0.3535888	total: 17.1s	remaining: 103ms
994:	learn: 0.3535708	total: 17.1s	remaining: 86.1ms
995:	learn: 0.3535377	total: 17.2s	remaining: 68.9ms
996:	learn: 0.3535145	total: 17.2s	remaining: 51.7ms
997:	learn: 0.3534733	total: 17.2s	remaining: 34.5ms
998:	learn: 0.3534493	total: 17.2s	remaining: 17.2ms
999:	learn: 0.3534286	total: 17.2s	remaining: 0us


VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('rf', RandomForestClassifier()),
                             ('gbm', GradientBoostingClassifier()),
                             ('xgb',
                              <catboost.core.CatBoostClassifier object at 0x00000253D6B024C0>),
                             ('cboost',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None,
                                            early_stopping_round...
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            n_estimators=100, n_jobs=None,
                                            num_parallel_tree=None,
                                            predictor=None, random_state=None,
                                            reg_alpha=None, reg_lambda=None, ...))],
                 voting='soft')

In [80]:
pred_vc=vc.predict_proba(newtest)

In [81]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':pred_vc[:,1]})

submission.to_csv('VotingModel(new).csv',index=False)

In [82]:
#  Lightgbm

from lightgbm import LGBMClassifier

lgbm=LGBMClassifier(n_estimators=550,max_depth=8,random_state=42,learning_rate=0.03,scale_pos_weight=3)

In [83]:
pred_lgbm=lgbm.fit(X,y).predict_proba(newtest)

In [84]:
pred_lgbm

array([[0.2085581 , 0.7914419 ],
       [0.78365066, 0.21634934],
       [0.89872873, 0.10127127],
       ...,
       [0.65965115, 0.34034885],
       [0.94642199, 0.05357801],
       [0.58338848, 0.41661152]])

In [85]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':pred_lgbm[:,1]})

submission.to_csv('LGBMModel(new).csv',index=False)

# RFECV and Cross Validation

In [86]:
from sklearn.tree import DecisionTreeClassifier

dtree=DecisionTreeClassifier()

from sklearn.feature_selection import RFECV

rfe=RFECV(estimator=dtree,step=1,min_features_to_select=5,cv=5,verbose=5)

In [87]:
rfe.fit(X,y)

Fitting estimator with 26 features.
Fitting estimator with 25 features.
Fitting estimator with 24 features.
Fitting estimator with 23 features.
Fitting estimator with 22 features.
Fitting estimator with 21 features.
Fitting estimator with 20 features.
Fitting estimator with 19 features.
Fitting estimator with 18 features.
Fitting estimator with 17 features.
Fitting estimator with 16 features.
Fitting estimator with 15 features.
Fitting estimator with 14 features.
Fitting estimator with 13 features.
Fitting estimator with 12 features.
Fitting estimator with 11 features.
Fitting estimator with 10 features.
Fitting estimator with 9 features.
Fitting estimator with 8 features.
Fitting estimator with 7 features.
Fitting estimator with 6 features.
Fitting estimator with 26 features.
Fitting estimator with 25 features.
Fitting estimator with 24 features.
Fitting estimator with 23 features.
Fitting estimator with 22 features.
Fitting estimator with 21 features.
Fitting estimator with 20 featur

RFECV(cv=5, estimator=DecisionTreeClassifier(), min_features_to_select=5,
      verbose=5)

In [88]:
features=list(rfe.get_feature_names_out())
print(features)

['Var1', 'Var2', 'Var5', 'Category1', 'Category2', 'Registration_Month', 'Registration_Year', 'Registration_Day', 'Camp_Start_Month', 'Camp_Start_Day', 'Camp_End_Month', 'Camp_End_Day', 'Online_Presence', 'Camp_Duration', 'Int_Day_Diff', 'HC_per_patient', 'Patient_per_HC', 'Patients_Per_Year', 'Patients_Per_Month', 'Patients_Per_End_Year', 'Patients_Per_End_Month']


In [89]:
# RFE Features

rfe_input=X.loc[:,features]
rfe_test=newtest.loc[:,features]

In [90]:
rfe_input.shape,rfe_test.shape

((52694, 21), (22584, 21))

In [91]:
#  Lightgbm

lgbm=LGBMClassifier(n_estimators=500,max_depth=10,random_state=42,learning_rate=0.01,scale_pos_weight=3)

pred_lgbm=lgbm.fit(rfe_input,y).predict_proba(rfe_test)
pred_lgbm

# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':pred_lgbm[:,1]})

submission.to_csv('RFE_Model(new).csv',index=False)

# Cross Validation for LGBM

In [92]:
from sklearn.model_selection import KFold

kfold=KFold(n_splits=5,shuffle=True) # 

lgbm=LGBMClassifier(n_estimators=500,max_depth=10,random_state=42,learning_rate=0.01,scale_pos_weight=3)

pred_df=pd.DataFrame()

n=5
for i in range(n):
    folds=next(kfold.split(X)) # helps to iterate between folds(here 5 folds)
    xtrain=X.iloc[folds[0]] # builds xtrain data
    ytrain=y.iloc[folds[0]] # creates y values
    lgbm.fit(xtrain,ytrain)
    pred_df[i]=lgbm.predict_proba(newtest)[:,1]

In [93]:
pred_df

0         1         2         3         4
0      0.796030  0.793010  0.798857  0.763803  0.778808
1      0.261178  0.225300  0.224581  0.240835  0.232709
2      0.152739  0.186854  0.152631  0.207491  0.151750
3      0.819709  0.845464  0.843825  0.819515  0.872541
4      0.237879  0.211472  0.218650  0.207773  0.242463
...         ...       ...       ...       ...       ...
22579  0.581996  0.571763  0.515145  0.570528  0.630876
22580  0.317808  0.266880  0.256616  0.302680  0.276534
22581  0.375439  0.351746  0.401477  0.360155  0.347649
22582  0.039091  0.053250  0.064428  0.052580  0.051116
22583  0.373635  0.363730  0.414540  0.473222  0.391738

[22584 rows x 5 columns]

In [94]:
median_prob=pred_df.median(axis=1)
median_prob

0        0.793010
1        0.232709
2        0.152739
3        0.843825
4        0.218650
           ...   
22579    0.571763
22580    0.276534
22581    0.360155
22582    0.052580
22583    0.391738
Length: 22584, dtype: float64

In [95]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':median_prob})

submission.to_csv('CV_Model(new).csv',index=False)

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

In [97]:
X=newtrain.drop('outcome',axis=1)
y=newtrain['outcome']

In [98]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,classification_report,cohen_kappa_score,f1_score

In [99]:
def validation(test,pred):
    print('Confusion Matrix\n',confusion_matrix(test,pred))
    print('Accuracy:\t',accuracy_score(test,pred))
    print('Precison:\t',precision_score(test,pred))
    print('Recall:\t',recall_score(test,pred))
    print('F1 Score:\t',f1_score(test,pred))
    print('Cohen-Kappa:\t',cohen_kappa_score(test,pred))
    print('Classification Report:\t\n',classification_report(test,pred))

In [100]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42,stratify=y)

In [101]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((36885, 26), (15809, 26), (36885,), (15809,))

In [102]:
def model_result(model,x_train,y_train,x_test,y_test):
    print(str(model))
    
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    validation(y_test,y_pred)
    
    y_pred_prob = model.predict_proba(x_test)[:,1]
    

In [103]:
model_result(LogisticRegression('l2'),x_train,y_train,x_test,y_test)

LogisticRegression()
Confusion Matrix
 [[11184   323]
 [ 4021   281]]
Accuracy:	 0.7252198114997787
Precison:	 0.4652317880794702
Recall:	 0.06531845653184565
F1 Score:	 0.11455360782715042
Cohen-Kappa:	 0.050963695959342914
Classification Report:	
               precision    recall  f1-score   support

           0       0.74      0.97      0.84     11507
           1       0.47      0.07      0.11      4302

    accuracy                           0.73     15809
   macro avg       0.60      0.52      0.48     15809
weighted avg       0.66      0.73      0.64     15809



In [104]:
y_pred_prob = LogisticRegression(penalty='l2').fit(X,y).predict_proba(newtest)
y_pred_prob

array([[0.74921594, 0.25078406],
       [0.67022592, 0.32977408],
       [0.53097556, 0.46902444],
       ...,
       [0.94085029, 0.05914971],
       [0.86837264, 0.13162736],
       [0.60658228, 0.39341772]])

In [105]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred_prob[:,1]})

submission.to_csv('Logistic_Model(new).csv',index=False)

In [106]:
model_result(KNeighborsClassifier(n_neighbors=15),x_train,y_train,x_test,y_test)

KNeighborsClassifier(n_neighbors=15)
Confusion Matrix
 [[10319  1188]
 [ 1931  2371]]
Accuracy:	 0.8027073186159782
Precison:	 0.6661983703287441
Recall:	 0.5511390051139005
F1 Score:	 0.6032311410761989
Cohen-Kappa:	 0.4734998686052616
Classification Report:	
               precision    recall  f1-score   support

           0       0.84      0.90      0.87     11507
           1       0.67      0.55      0.60      4302

    accuracy                           0.80     15809
   macro avg       0.75      0.72      0.74     15809
weighted avg       0.79      0.80      0.80     15809



In [107]:
y_pred=KNeighborsClassifier(n_neighbors=15).fit(X,y).predict_proba(newtest)
y_pred

array([[0.66666667, 0.33333333],
       [0.93333333, 0.06666667],
       [0.8       , 0.2       ],
       ...,
       [0.86666667, 0.13333333],
       [0.93333333, 0.06666667],
       [0.93333333, 0.06666667]])

In [108]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred[:,1]})

submission.to_csv('KNeighbor_Model(new).csv',index=False)

In [109]:
model_result(GaussianNB(),x_train,y_train,x_test,y_test)

GaussianNB()
Confusion Matrix
 [[10266  1241]
 [ 2689  1613]]
Accuracy:	 0.7514074261496616
Precison:	 0.5651716888577435
Recall:	 0.3749418874941888
F1 Score:	 0.45081050866405814
Cohen-Kappa:	 0.2985548887437839
Classification Report:	
               precision    recall  f1-score   support

           0       0.79      0.89      0.84     11507
           1       0.57      0.37      0.45      4302

    accuracy                           0.75     15809
   macro avg       0.68      0.63      0.65     15809
weighted avg       0.73      0.75      0.73     15809



In [110]:
model_result(DecisionTreeClassifier(max_depth=7),x_train,y_train,x_test,y_test)

DecisionTreeClassifier(max_depth=7)
Confusion Matrix
 [[10434  1073]
 [ 1879  2423]]
Accuracy:	 0.8132709216269214
Precison:	 0.6930778032036613
Recall:	 0.5632264063226406
F1 Score:	 0.621441395229546
Cohen-Kappa:	 0.4992632002331183
Classification Report:	
               precision    recall  f1-score   support

           0       0.85      0.91      0.88     11507
           1       0.69      0.56      0.62      4302

    accuracy                           0.81     15809
   macro avg       0.77      0.73      0.75     15809
weighted avg       0.81      0.81      0.81     15809



In [111]:
y_pred =DecisionTreeClassifier(max_depth=7).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [112]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('DT_Model(new).csv',index=False)

In [113]:
model_result(RandomForestClassifier(n_estimators=350,max_depth=10),x_train,y_train,x_test,y_test)

RandomForestClassifier(max_depth=10, n_estimators=350)
Confusion Matrix
 [[10459  1048]
 [ 1805  2497]]
Accuracy:	 0.8195331773040673
Precison:	 0.7043723554301834
Recall:	 0.5804277080427708
F1 Score:	 0.6364215623805276
Cohen-Kappa:	 0.5178825009732818
Classification Report:	
               precision    recall  f1-score   support

           0       0.85      0.91      0.88     11507
           1       0.70      0.58      0.64      4302

    accuracy                           0.82     15809
   macro avg       0.78      0.74      0.76     15809
weighted avg       0.81      0.82      0.81     15809



In [114]:
y_pred =RandomForestClassifier(n_estimators=350,max_depth=10).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [115]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('RF_Model(new2).csv',index=False)

In [116]:
model_result(GradientBoostingClassifier(n_estimators=400,max_depth=6),x_train,y_train,x_test,y_test)

GradientBoostingClassifier(max_depth=6, n_estimators=400)
Confusion Matrix
 [[10412  1095]
 [ 1693  2609]]
Accuracy:	 0.8236447593143146
Precison:	 0.7043736501079914
Recall:	 0.606462110646211
F1 Score:	 0.6517611791156632
Cohen-Kappa:	 0.5345660891774302
Classification Report:	
               precision    recall  f1-score   support

           0       0.86      0.90      0.88     11507
           1       0.70      0.61      0.65      4302

    accuracy                           0.82     15809
   macro avg       0.78      0.76      0.77     15809
weighted avg       0.82      0.82      0.82     15809



In [117]:
y_pred =GradientBoostingClassifier(n_estimators=400,max_depth=6).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [118]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('GB_Model(new1).csv',index=False)

In [119]:
model_result(LGBMClassifier(scale_pos_weight=1,n_estimators=400,num_leaves=30),x_train,y_train,x_test,y_test)

LGBMClassifier(n_estimators=400, num_leaves=30, scale_pos_weight=1)
Confusion Matrix
 [[10425  1082]
 [ 1698  2604]]
Accuracy:	 0.8241508001771143
Precison:	 0.7064568638090071
Recall:	 0.6052998605299861
F1 Score:	 0.6519779669504256
Cohen-Kappa:	 0.5352651619341471
Classification Report:	
               precision    recall  f1-score   support

           0       0.86      0.91      0.88     11507
           1       0.71      0.61      0.65      4302

    accuracy                           0.82     15809
   macro avg       0.78      0.76      0.77     15809
weighted avg       0.82      0.82      0.82     15809



In [120]:
y_pred =LGBMClassifier(scale_pos_weight=1,n_estimators=400,num_leaves=30).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [121]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('LGBM_Model(new2).csv',index=False)

# GridSearchCV

In [122]:
from sklearn.model_selection import GridSearchCV

In [123]:
params = {'learning_rate':[0.001,0.01,0.1,1,10,10.1],
         'n_estimators':[200,250,300,400,500],
         'max_depth':[4,5,6,7,8,9]}

In [124]:
gscv = GridSearchCV(estimator=LGBMClassifier(),
                   param_grid=params,
                   scoring='f1',
                   cv=3,
                   verbose=3)

In [125]:
gscv.fit(x_train,y_train)

Fitting 3 folds for each of 180 candidates, totalling 540 fits
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=200;, score=0.000 total time=   0.5s
[CV 2/3] END learning_rate=0.001, max_depth=4, n_estimators=200;, score=0.000 total time=   0.5s
[CV 3/3] END learning_rate=0.001, max_depth=4, n_estimators=200;, score=0.000 total time=   0.5s
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=250;, score=0.000 total time=   0.6s
[CV 2/3] END learning_rate=0.001, max_depth=4, n_estimators=250;, score=0.000 total time=   0.6s
[CV 3/3] END learning_rate=0.001, max_depth=4, n_estimators=250;, score=0.000 total time=   0.7s
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=300;, score=0.000 total time=   0.7s
[CV 2/3] END learning_rate=0.001, max_depth=4, n_estimators=300;, score=0.000 total time=   0.8s
[CV 3/3] END learning_rate=0.001, max_depth=4, n_estimators=300;, score=0.000 total time=   0.7s
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=400;

[CV 1/3] END learning_rate=0.001, max_depth=9, n_estimators=400;, score=0.000 total time=   0.7s
[CV 2/3] END learning_rate=0.001, max_depth=9, n_estimators=400;, score=0.000 total time=   0.9s
[CV 3/3] END learning_rate=0.001, max_depth=9, n_estimators=400;, score=0.000 total time=   0.8s
[CV 1/3] END learning_rate=0.001, max_depth=9, n_estimators=500;, score=0.027 total time=   1.2s
[CV 2/3] END learning_rate=0.001, max_depth=9, n_estimators=500;, score=0.027 total time=   1.0s
[CV 3/3] END learning_rate=0.001, max_depth=9, n_estimators=500;, score=0.028 total time=   1.0s
[CV 1/3] END learning_rate=0.01, max_depth=4, n_estimators=200;, score=0.602 total time=   0.3s
[CV 2/3] END learning_rate=0.01, max_depth=4, n_estimators=200;, score=0.597 total time=   0.2s
[CV 3/3] END learning_rate=0.01, max_depth=4, n_estimators=200;, score=0.597 total time=   0.3s
[CV 1/3] END learning_rate=0.01, max_depth=4, n_estimators=250;, score=0.613 total time=   0.4s
[CV 2/3] END learning_rate=0.01, m

[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=250;, score=0.627 total time=   0.5s
[CV 1/3] END learning_rate=0.01, max_depth=9, n_estimators=300;, score=0.627 total time=   0.6s
[CV 2/3] END learning_rate=0.01, max_depth=9, n_estimators=300;, score=0.634 total time=   0.6s
[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=300;, score=0.629 total time=   0.6s
[CV 1/3] END learning_rate=0.01, max_depth=9, n_estimators=400;, score=0.637 total time=   0.8s
[CV 2/3] END learning_rate=0.01, max_depth=9, n_estimators=400;, score=0.643 total time=   0.8s
[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=400;, score=0.632 total time=   0.9s
[CV 1/3] END learning_rate=0.01, max_depth=9, n_estimators=500;, score=0.639 total time=   1.1s
[CV 2/3] END learning_rate=0.01, max_depth=9, n_estimators=500;, score=0.645 total time=   1.0s
[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=500;, score=0.635 total time=   1.2s
[CV 1/3] END learning_rate=0.1, max_dept

[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=200;, score=0.644 total time=   0.3s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_estimators=250;, score=0.653 total time=   0.3s
[CV 2/3] END learning_rate=0.1, max_depth=9, n_estimators=250;, score=0.652 total time=   0.4s
[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=250;, score=0.644 total time=   0.4s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_estimators=300;, score=0.653 total time=   0.4s
[CV 2/3] END learning_rate=0.1, max_depth=9, n_estimators=300;, score=0.653 total time=   0.4s
[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=300;, score=0.645 total time=   0.5s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_estimators=400;, score=0.653 total time=   0.7s
[CV 2/3] END learning_rate=0.1, max_depth=9, n_estimators=400;, score=0.653 total time=   0.6s
[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=400;, score=0.645 total time=   0.6s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_est

[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=200;, score=0.600 total time=   0.2s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=200;, score=0.596 total time=   0.2s
[CV 3/3] END learning_rate=1, max_depth=9, n_estimators=200;, score=0.593 total time=   0.2s
[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=250;, score=0.600 total time=   0.4s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=250;, score=0.587 total time=   0.4s
[CV 3/3] END learning_rate=1, max_depth=9, n_estimators=250;, score=0.595 total time=   0.4s
[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=300;, score=0.599 total time=   0.4s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=300;, score=0.570 total time=   0.4s
[CV 3/3] END learning_rate=1, max_depth=9, n_estimators=300;, score=0.596 total time=   0.4s
[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=400;, score=0.596 total time=   0.6s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=400;, score=0.

[CV 2/3] END learning_rate=10, max_depth=8, n_estimators=500;, score=0.554 total time=   0.5s
[CV 3/3] END learning_rate=10, max_depth=8, n_estimators=500;, score=0.300 total time=   0.5s
[CV 1/3] END learning_rate=10, max_depth=9, n_estimators=200;, score=0.525 total time=   0.2s
[CV 2/3] END learning_rate=10, max_depth=9, n_estimators=200;, score=0.554 total time=   0.1s
[CV 3/3] END learning_rate=10, max_depth=9, n_estimators=200;, score=0.311 total time=   0.1s
[CV 1/3] END learning_rate=10, max_depth=9, n_estimators=250;, score=0.525 total time=   0.2s
[CV 2/3] END learning_rate=10, max_depth=9, n_estimators=250;, score=0.554 total time=   0.2s
[CV 3/3] END learning_rate=10, max_depth=9, n_estimators=250;, score=0.311 total time=   0.2s
[CV 1/3] END learning_rate=10, max_depth=9, n_estimators=300;, score=0.525 total time=   0.2s
[CV 2/3] END learning_rate=10, max_depth=9, n_estimators=300;, score=0.554 total time=   0.2s
[CV 3/3] END learning_rate=10, max_depth=9, n_estimators=300

[CV 1/3] END learning_rate=10.1, max_depth=8, n_estimators=400;, score=0.536 total time=   0.3s
[CV 2/3] END learning_rate=10.1, max_depth=8, n_estimators=400;, score=0.469 total time=   0.4s
[CV 3/3] END learning_rate=10.1, max_depth=8, n_estimators=400;, score=0.364 total time=   0.4s
[CV 1/3] END learning_rate=10.1, max_depth=8, n_estimators=500;, score=0.536 total time=   0.4s
[CV 2/3] END learning_rate=10.1, max_depth=8, n_estimators=500;, score=0.469 total time=   0.4s
[CV 3/3] END learning_rate=10.1, max_depth=8, n_estimators=500;, score=0.364 total time=   0.5s
[CV 1/3] END learning_rate=10.1, max_depth=9, n_estimators=200;, score=0.544 total time=   0.2s
[CV 2/3] END learning_rate=10.1, max_depth=9, n_estimators=200;, score=0.466 total time=   0.2s
[CV 3/3] END learning_rate=10.1, max_depth=9, n_estimators=200;, score=0.388 total time=   0.1s
[CV 1/3] END learning_rate=10.1, max_depth=9, n_estimators=250;, score=0.544 total time=   0.2s
[CV 2/3] END learning_rate=10.1, max_dep

GridSearchCV(cv=3, estimator=LGBMClassifier(),
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10, 10.1],
                         'max_depth': [4, 5, 6, 7, 8, 9],
                         'n_estimators': [200, 250, 300, 400, 500]},
             scoring='f1', verbose=3)

In [126]:
gscv.best_score_

0.650405191403206

In [127]:
gscv.best_params_

{'learning_rate': 0.1, 'max_depth': 9, 'n_estimators': 400}

In [128]:
model_result(LGBMClassifier(**gscv.best_params_),x_train,y_train,x_test,y_test)

LGBMClassifier(max_depth=9, n_estimators=400)
Confusion Matrix
 [[10433  1074]
 [ 1704  2598]]
Accuracy:	 0.8242773103928143
Precison:	 0.7075163398692811
Recall:	 0.603905160390516
F1 Score:	 0.6516177577125658
Cohen-Kappa:	 0.5351036262601454
Classification Report:	
               precision    recall  f1-score   support

           0       0.86      0.91      0.88     11507
           1       0.71      0.60      0.65      4302

    accuracy                           0.82     15809
   macro avg       0.78      0.76      0.77     15809
weighted avg       0.82      0.82      0.82     15809



In [129]:
y_pred =LGBMClassifier(**gscv.best_params_).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [131]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('GSCV_LGBM_Model(new).csv',index=False)

In [136]:
model_result(XGBClassifier(objective="binary:logistic",random_state=5),x_train,y_train,x_test,y_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, gamma=None,
              gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, predictor=None, random_state=5,
              reg_alpha=None, reg_lambda=None, ...)
Confusion Matrix
 [[10424  1083]
 [ 1703  2599]]
Accuracy:	 0.8237712695300146
Precison:	 0.7058663769690385
Recall:	 0.604137610413761
F1 Score:	 0.6510521042084169
Cohen-Kappa:	 0.5341201581635067
Classification Report:	
               precision    recall  f1-

In [137]:
y_pred =XGBClassifier(objective="binary:logistic",random_state=5).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [138]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('XGB_Model(new).csv',index=False)

In [145]:
model_result(XGBClassifier(objective="binary:logistic",n_estimators=500,random_state=420),x_train,y_train,x_test,y_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, gamma=None,
              gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, predictor=None, random_state=420,
              reg_alpha=None, reg_lambda=None, ...)
Confusion Matrix
 [[10286  1221]
 [ 1669  2633]]
Accuracy:	 0.8171927383136188
Precison:	 0.6831862999481059
Recall:	 0.6120409112040911
F1 Score:	 0.6456596370769985
Cohen-Kappa:	 0.5229820531120235
Classification Report:	
               precision    recall  

In [146]:
gscv = GridSearchCV(estimator=XGBClassifier(),
                   param_grid=params,
                   scoring='f1',
                   cv=3,
                   verbose=3)

In [147]:
gscv.fit(x_train,y_train)

Fitting 3 folds for each of 180 candidates, totalling 540 fits
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=200;, score=0.609 total time=   1.4s
[CV 2/3] END learning_rate=0.001, max_depth=4, n_estimators=200;, score=0.609 total time=   1.3s
[CV 3/3] END learning_rate=0.001, max_depth=4, n_estimators=200;, score=0.570 total time=   1.3s
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=250;, score=0.612 total time=   1.7s
[CV 2/3] END learning_rate=0.001, max_depth=4, n_estimators=250;, score=0.628 total time=   1.7s
[CV 3/3] END learning_rate=0.001, max_depth=4, n_estimators=250;, score=0.611 total time=   1.8s
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=300;, score=0.612 total time=   2.2s
[CV 2/3] END learning_rate=0.001, max_depth=4, n_estimators=300;, score=0.625 total time=   2.5s
[CV 3/3] END learning_rate=0.001, max_depth=4, n_estimators=300;, score=0.611 total time=   2.5s
[CV 1/3] END learning_rate=0.001, max_depth=4, n_estimators=400;

[CV 1/3] END learning_rate=0.001, max_depth=9, n_estimators=400;, score=0.620 total time=   9.2s
[CV 2/3] END learning_rate=0.001, max_depth=9, n_estimators=400;, score=0.630 total time=   9.3s
[CV 3/3] END learning_rate=0.001, max_depth=9, n_estimators=400;, score=0.613 total time=   9.2s
[CV 1/3] END learning_rate=0.001, max_depth=9, n_estimators=500;, score=0.624 total time=  11.7s
[CV 2/3] END learning_rate=0.001, max_depth=9, n_estimators=500;, score=0.636 total time=  13.2s
[CV 3/3] END learning_rate=0.001, max_depth=9, n_estimators=500;, score=0.611 total time=  12.0s
[CV 1/3] END learning_rate=0.01, max_depth=4, n_estimators=200;, score=0.617 total time=   1.7s
[CV 2/3] END learning_rate=0.01, max_depth=4, n_estimators=200;, score=0.608 total time=   1.7s
[CV 3/3] END learning_rate=0.01, max_depth=4, n_estimators=200;, score=0.607 total time=   1.7s
[CV 1/3] END learning_rate=0.01, max_depth=4, n_estimators=250;, score=0.624 total time=   2.1s
[CV 2/3] END learning_rate=0.01, m

[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=250;, score=0.635 total time=   5.6s
[CV 1/3] END learning_rate=0.01, max_depth=9, n_estimators=300;, score=0.643 total time=   6.8s
[CV 2/3] END learning_rate=0.01, max_depth=9, n_estimators=300;, score=0.656 total time=   6.7s
[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=300;, score=0.637 total time=   7.0s
[CV 1/3] END learning_rate=0.01, max_depth=9, n_estimators=400;, score=0.644 total time=   8.8s
[CV 2/3] END learning_rate=0.01, max_depth=9, n_estimators=400;, score=0.656 total time=   8.8s
[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=400;, score=0.637 total time=   8.8s
[CV 1/3] END learning_rate=0.01, max_depth=9, n_estimators=500;, score=0.645 total time=  10.8s
[CV 2/3] END learning_rate=0.01, max_depth=9, n_estimators=500;, score=0.659 total time=  10.7s
[CV 3/3] END learning_rate=0.01, max_depth=9, n_estimators=500;, score=0.638 total time=  10.9s
[CV 1/3] END learning_rate=0.1, max_dept

[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=200;, score=0.637 total time=   3.7s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_estimators=250;, score=0.642 total time=   4.7s
[CV 2/3] END learning_rate=0.1, max_depth=9, n_estimators=250;, score=0.649 total time=   4.7s
[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=250;, score=0.635 total time=   4.7s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_estimators=300;, score=0.639 total time=   5.6s
[CV 2/3] END learning_rate=0.1, max_depth=9, n_estimators=300;, score=0.647 total time=   5.6s
[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=300;, score=0.635 total time=   5.6s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_estimators=400;, score=0.639 total time=   7.5s
[CV 2/3] END learning_rate=0.1, max_depth=9, n_estimators=400;, score=0.643 total time=   7.4s
[CV 3/3] END learning_rate=0.1, max_depth=9, n_estimators=400;, score=0.636 total time=   7.5s
[CV 1/3] END learning_rate=0.1, max_depth=9, n_est

[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=200;, score=0.607 total time=   3.9s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=200;, score=0.611 total time=   4.0s
[CV 3/3] END learning_rate=1, max_depth=9, n_estimators=200;, score=0.612 total time=   3.9s
[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=250;, score=0.608 total time=   4.9s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=250;, score=0.614 total time=   5.3s
[CV 3/3] END learning_rate=1, max_depth=9, n_estimators=250;, score=0.610 total time=   5.0s
[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=300;, score=0.610 total time=   5.8s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=300;, score=0.613 total time=   5.8s
[CV 3/3] END learning_rate=1, max_depth=9, n_estimators=300;, score=0.611 total time=   5.8s
[CV 1/3] END learning_rate=1, max_depth=9, n_estimators=400;, score=0.607 total time=   8.0s
[CV 2/3] END learning_rate=1, max_depth=9, n_estimators=400;, score=0.

[CV 2/3] END learning_rate=10, max_depth=8, n_estimators=500;, score=0.598 total time=   1.9s
[CV 3/3] END learning_rate=10, max_depth=8, n_estimators=500;, score=0.622 total time=   1.9s
[CV 1/3] END learning_rate=10, max_depth=9, n_estimators=200;, score=0.498 total time=   0.7s
[CV 2/3] END learning_rate=10, max_depth=9, n_estimators=200;, score=0.580 total time=   0.8s
[CV 3/3] END learning_rate=10, max_depth=9, n_estimators=200;, score=0.433 total time=   0.8s
[CV 1/3] END learning_rate=10, max_depth=9, n_estimators=250;, score=0.498 total time=   1.0s
[CV 2/3] END learning_rate=10, max_depth=9, n_estimators=250;, score=0.580 total time=   0.9s
[CV 3/3] END learning_rate=10, max_depth=9, n_estimators=250;, score=0.433 total time=   1.0s
[CV 1/3] END learning_rate=10, max_depth=9, n_estimators=300;, score=0.498 total time=   1.1s
[CV 2/3] END learning_rate=10, max_depth=9, n_estimators=300;, score=0.580 total time=   1.1s
[CV 3/3] END learning_rate=10, max_depth=9, n_estimators=300

[CV 1/3] END learning_rate=10.1, max_depth=8, n_estimators=400;, score=0.627 total time=   1.5s
[CV 2/3] END learning_rate=10.1, max_depth=8, n_estimators=400;, score=0.606 total time=   1.5s
[CV 3/3] END learning_rate=10.1, max_depth=8, n_estimators=400;, score=0.622 total time=   1.5s
[CV 1/3] END learning_rate=10.1, max_depth=8, n_estimators=500;, score=0.627 total time=   1.9s
[CV 2/3] END learning_rate=10.1, max_depth=8, n_estimators=500;, score=0.606 total time=   1.9s
[CV 3/3] END learning_rate=10.1, max_depth=8, n_estimators=500;, score=0.622 total time=   1.8s
[CV 1/3] END learning_rate=10.1, max_depth=9, n_estimators=200;, score=0.413 total time=   0.7s
[CV 2/3] END learning_rate=10.1, max_depth=9, n_estimators=200;, score=0.600 total time=   0.7s
[CV 3/3] END learning_rate=10.1, max_depth=9, n_estimators=200;, score=0.441 total time=   0.8s
[CV 1/3] END learning_rate=10.1, max_depth=9, n_estimators=250;, score=0.413 total time=   1.0s
[CV 2/3] END learning_rate=10.1, max_dep

GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     gamma=None, gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_ca...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None,
                                     num_parallel_tree=None, predictor=None,
                                     random_state=None, reg_alpha=None,
                                     reg_lambda=None, ...),
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10, 10.1],
                         'max_depth': [4, 5, 6, 7, 8, 9],
                         'n_estimators': [200, 250, 300, 400, 500]},
             scoring='f1', verbose=3)

In [148]:
gscv.best_score_

0.6489574909330719

In [149]:
gscv.best_params_

{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 300}

In [150]:
model_result(XGBClassifier(**gscv.best_params_),x_train,y_train,x_test,y_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, gamma=None,
              gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, predictor=None, random_state=None,
              reg_alpha=None, reg_lambda=None, ...)
Confusion Matrix
 [[10416  1091]
 [ 1714  2588]]
Accuracy:	 0.8225694224808653
Precison:	 0.7034520250067954
Recall:	 0.601580660158066
F1 Score:	 0.6485402831725348
Cohen-Kappa:	 0.5308356769818944
Classification Report:	
               precision    recall  f1-s

In [151]:
y_pred =XGBClassifier(**gscv.best_params_,random_state=5).fit(X,y).predict(newtest)
y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [152]:
# Submission DataFrame

submission=pd.DataFrame({'Patient_ID':test.Patient_ID,'outcome':y_pred})

submission.to_csv('GSCV_XGB_Model(new1).csv',index=False)